name: update readme

on: 
  push:
    branches:
     - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: junxnone/update-readme
        with:
          work_branch: "main"
          push_branch: "gh-page"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          actor: ${{ github.actor }}
